# only fastapi since postgres and minio are deployed on external services

version: "3.9"

services:
  fastapi:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
