from typing import List

from fastapi import APIRouter, HTTPException, Depends, Path
from pydantic import BaseModel

from core.database import get_db
from core.security import get_current_user
from crud.chat import add_workout_to_history, remove_from_favorites, add_to_favorites, \
    get_user_history, get_user_favorites_as_history
from crud.user_gym_logs import get_user_gym_logs
from crud.workout_generator import generate_workout
from model.user import User
from sqlalchemy.orm import Session

from schemas.chat import WorkoutGenerateResponse, ChatHistoryResponse

router = APIRouter(prefix="/workout", tags=["workout"])


class WorkoutRequest(BaseModel):
    goal: str


@router.post(
    "/generate",
    response_model=WorkoutGenerateResponse,
    summary="Generate workout program",
    description="Creates a personalized workout program based on the user's goal, age, and gender.",
    responses={
        200: {"description": "Workout program successfully generated"},
        500: {"description": "Server error occurred while generating the workout"}
    },
    response_model_exclude_none=True,
)
def generate_workout_plan(
        req: WorkoutRequest,
        db: Session = Depends(get_db),
        current_user: User = Depends(get_current_user)
):
    """
    Generates a workout program based on the user's specified goal.
    """
    prompt = f"Create a workout program for {req.goal}."
    try:
        user_logs = get_user_gym_logs(db, current_user.id)
        age = current_user.age
        gender = current_user.gender
        workout = generate_workout(prompt, user_logs, age, gender)
        return add_workout_to_history(db, current_user.id, req.goal, workout)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate workout: {str(e)}")


@router.get(
    "/history",
    response_model=List[ChatHistoryResponse],
    summary="User workout history",
    description="Returns a list of all workouts generated by the user.",
    responses={
        200: {"description": "Workout history retrieved successfully"},
        500: {"description": "Server error occurred while retrieving history"}
    }
)
def get_workout_history(
        db: Session = Depends(get_db),
        current_user: User = Depends(get_current_user)
):
    """
    Retrieve the full history of workouts generated by the user.
    """
    return get_user_history(db, current_user.id)


@router.post(
    "/favorite/{history_id}",
    summary="Add workout to favorites",
    description="Adds a workout from the history to the user's list of favorites.",
    responses={
        200: {"description": "Workout successfully added to favorites"},
        404: {"description": "Workout history entry not found"}
    }
)
def add_favorite(
    history_id: int = Path(..., description="ID of the workout history entry"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    return add_to_favorites(db, current_user.id, history_id)


@router.delete(
    "/favorite/{history_id}",
    summary="Remove workout from favorites",
    description="Removes a workout from the user's favorites list.",
    responses={
        200: {"description": "Workout successfully removed from favorites"},
        404: {"description": "Workout not found in favorites"}
    }
)
def remove_favorite(
    history_id: int = Path(..., description="ID of the workout history entry"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    result = remove_from_favorites(db, current_user.id, history_id)
    if not result:
        raise HTTPException(status_code=404, detail="Not found in favorites")
    return {"detail": "Removed from favorites"}


@router.get(
    "/favorites",
    response_model=List[ChatHistoryResponse],
    summary="Get favorite workouts",
    description="Returns a list of the user's favorite workouts.",
    responses={
        200: {"description": "Favorite workouts retrieved successfully"},
        500: {"description": "Server error occurred while retrieving favorites"}
    }
)
def get_favorites(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    return get_user_favorites_as_history(db, current_user.id)
